// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAym3_mh8IVzRBvtZFtf3327y3HWPLgvEM',
    appId: '1:1076211545924:web:111e04558b92d048f6c911',
    messagingSenderId: '1076211545924',
    projectId: 'final-exam-adv-flutter',
    authDomain: 'final-exam-adv-flutter.firebaseapp.com',
    storageBucket: 'final-exam-adv-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JDMcfVfuysxly2sNsFvdTuGB9USmWHc',
    appId: '1:1076211545924:android:dae3ce1fbd5ac3aef6c911',
    messagingSenderId: '1076211545924',
    projectId: 'final-exam-adv-flutter',
    storageBucket: 'final-exam-adv-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQkbta5QzW6ipo2yu5yBRlqkbww3BTRk',
    appId: '1:1076211545924:ios:a2d11458edcbccc1f6c911',
    messagingSenderId: '1076211545924',
    projectId: 'final-exam-adv-flutter',
    storageBucket: 'final-exam-adv-flutter.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrQkbta5QzW6ipo2yu5yBRlqkbww3BTRk',
    appId: '1:1076211545924:ios:a2d11458edcbccc1f6c911',
    messagingSenderId: '1076211545924',
    projectId: 'final-exam-adv-flutter',
    storageBucket: 'final-exam-adv-flutter.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAym3_mh8IVzRBvtZFtf3327y3HWPLgvEM',
    appId: '1:1076211545924:web:d9b2a12768339858f6c911',
    messagingSenderId: '1076211545924',
    projectId: 'final-exam-adv-flutter',
    authDomain: 'final-exam-adv-flutter.firebaseapp.com',
    storageBucket: 'final-exam-adv-flutter.appspot.com',
  );
}
